
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory-service
    username: springstudent
    password: springstudent
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: inventory-service
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect


server:
  port: 9991

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka